language: python
python:
  - "3.8"
services:
  - postgresql
before_script:
  - psql -c 'create database db;' -U postgres
  - psql -c 'create database db_test;' -U postgres
  - psql -c 'create role root superuser;' -U postgres
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - TESTING=1 pytest
