version: "2"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init/create_databases.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/docker/postgres/mastermind:/var/lib/postgresql/data
      # - ./init/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./init/limits.conf:/etc/security/limits.conf
    restart: always
    ports:
      - 5432:5432
